INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (1, "Task Characteristics", "Work Scheduling AutoNnomy", "Work scheduling autonomy means that you are able to determine when, and the order in which, you complete your work tasks without having to check in with a supervisor or coworkers.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (2, "Task Characteristics", "Decision Making Autonomy", "Decision making autonomy means that you are able to make decisions about various aspects of your work without having to check in with a supervisor or coworkers.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (3, "Task Characteristics", "Work Methods Autonomy", "Work methods autonomy means that you are able to choose the approach and methods you use for your work without having to check in with a supervisor or coworker.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (4, "Task Characteristics", "Task Variety", "Task variety means that the work you do involves a lot of different kinds tasks and activities, with relatively little time spent doing the same things over and over.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (5, "Task Characteristics", "Task Significance", "Task significance means that the work that you do has â€“ or can have â€“ an important direct or indirect impact on the lives of other people.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (6, "Task Characteristics", "Task Identity", "Task identity means that your work has an identifiable stating point, and ending point, so you know when youâ€™ve â€˜finishedâ€™ something.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (7, "Task Characteristics", "Feedback from Job", "Feedback from the job means that your work provides you with clear information relating to the quality and quantity of your job performance.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (8, "Knowledge Characteristics", "Job Complexity", "Job complexity means that your job requires you to work on multiple, often complicated, tasks simultaneously.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (9, "Knowledge Characteristics", "Information Processing", "Information processing means that your job requires you to keep track of and analyze a large amount of information in order to complete your work.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (10, "Knowledge Characteristics", "Problem Solving", "Problem solving means that your job requires you be creative in finding solutions to problems with no conspicuous or obvious answer.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (11, "Knowledge Characteristics", "Skill Variety", "Skill variety means that your job requires you to use a range of different or high-level skills to complete your work tasks.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (12, "Knowledge Characteristics", "Specialization", "Specialization means that your job requires you to have well-developed knowledge, and a focused set of skills, in order to complete your work.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (13, "Social characteristics", "Social Support", "Social support means that your job provides you with the opportunity to develop meaningful personal connections with your coworkers.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (14, "Social characteristics", "Initiated Interdependence", "Initiated interdependence means that for others to complete their work, including coworkers, depends on you getting your work done first.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (15, "Social characteristics", "Received Interdependence", "Received interdependence means that in order for you to complete your work that others, including coworkers, must complete their work first.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (16, "Social characteristics", "Interaction Outside Research Group", "Interaction outside the research group means that your job requires you to have frequent interactions and communication with people outside of your team or group in order to complete your work.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (17, "Social characteristics", "Faculty/project leader feedback", "Faculty/project leader feedback means that, while on the job, your faculty/project leader provides you with useful information about your work performance.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (18, "Social characteristics", "Peer Feedback", "Peer feedback means that, while on the job, your peers provide you with useful information about your work performance");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (19, "Work Context", "Ergonomics", "Ergonomics means that the physical configuration of your work space is generally comfortable, can accommodate a range of different body types, and doesnâ€™t contribute to physical strain or discomfort.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (20, "Work Context", "Physical Demands", "Physical demands means that, while on the job, a great deal of physical effort is necessary to complete your work tasks.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (21, "Work Context", "Work Conditions", "Work conditions means that the physical setting where you do your job tasks is generally free from uncomfortable or dangerous conditions.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (22, "Work Context", "Equipment Use", "Equipment use means that, while on the job, your work requires you to use a number of different kinds of equipment to complete your work tasks.");
INSERT INTO JobDescriptors (Id, Dimension, Characteristic, Description) VALUES (23, "Work Context", "Setting", "Work setting can vary in regards to how time is spent between the laboratory (working with reagents and equipment), computers (working with files), fieldwork (collecting samples or making observations in the natural environment) and working with people (teaching, sales, management work).");
INSERT INTO Surveys (Title, Name, Description) VALUES ("URE Experience", "Undergratuate Research Experience Survey", "This survey asks you to share your undergraduate research experience. As a result of you taking this survey, we will try to recommend a variety of possible jobs and careers.");
INSERT INTO Surveys (Title, Name, Description) VALUES ("Work Experience", "Work Experience Survey", "This survey asks you to share your work experience.");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("anonymous", Null, "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Morgan Has", "MHas366@icloud.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Oscar Loson", "OLoson560@yahoo.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Sydney Leasure", "SLeasure615@hotmail.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Octavio Talsma", "OTalsma32@yahoo.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Vern Bosley", "VBosley84@yahoo.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Monte Wendlandt", "MWendlandt412@msn.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Bethanie Tankson", "BTankson35@icloud.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Chris Hapeman", "CHapeman182@yahoo.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Andrew Mesia", "AMesia23@hotmail.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Reginald Spiva", "RSpiva579@icloud.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Lajuana Battenhouse", "LBattenhouse794@icloud.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Lin Isreal", "LIsreal918@icloud.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Wilber Gavette", "WGavette477@yahoo.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Andreas Wiechert", "AWiechert153@icloud.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Michel Seabrook", "MSeabrook945@icloud.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Tamisha Melgar", "TMelgar570@msn.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Maurice Dalbeck", "MDalbeck773@yahoo.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Suanne Phaymany", "SPhaymany50@yahoo.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Dean Zimbelman", "DZimbelman148@hotmail.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Salome Lawhead", "SLawhead118@gmail.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Arvilla Mcclurg", "AMcclurg955@hotmail.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Shery Snyder", "SSnyder946@yahoo.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Jong Underkofler", "JUnderkofler587@hotmail.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Michel Aderhold", "MAderhold29@yahoo.com", "Student");
INSERT INTO UserAccounts (UserName, Notes, Category) VALUES ("Armando Eichman", "AEichman151@msn.com", "Student");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (None, None, Null, None, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 1.0, "What is the primary discipline of your research?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 2.0, "How many undergraduate students, including yourself, are/were in your research group at the time of your participation?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 3.0, "How many people in total were in your research group?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 4.0, "Who was primarily responsible for mentoring and expert advice related to your research?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 5.0, "What was the primary setting for your research?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 6.0, "Approximately how was your research time distributed between settings?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 7.0, "How many hours per week did you work on research-related activities in your most recent research experience?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 8.0, "During the same time period, how many hours per week did you devote to extracurricular activities (such as clubs, volunteering, sports, music or theater, other hobbies)?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 9.0, "During the same time period, how many hours per week did you work in a paid job unrelated to your research (on campus or off campus).", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 10.0, "During the same time period, how many hours per week did you devote to other commitments or obligations that were not listed above? (e.g. caring for family members, unpaid work in a family business).", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 11.0, " During the same time period, what was your status in terms of academic courses or units?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 12.0, "The research position allows me to make my own decisions about how to schedule my work.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 13.0, "The research position allows me to decide on the order in which things are done.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 14.0, "The research position allows me to plan how I do my work.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 15.0, "The research position gives me a chance to use my personal initiative or judgment in carrying out the work.", 1.0, "decision making autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 16.0, "The research position allows me to make a lot of decisions on my own.", 1.0, "decision making autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 17.0, "The research position provides me with significant autonomy in making decisions.", 1.0, "decision making autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 18.0, "The research position allows me to make decisions about what methods I use to complete my work.", 1.0, "work methods autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 19.0, "The research position gives me considerable opportunity for independence and freedom in how I do the work.", 1.0, "work methods autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 20.0, "The research position allows me to decide on my own how to go about doing my work.", 1.0, "work methods autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 21.0, "The research position involves a great deal of task variety.", 1.0, "task variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 22.0, "The research position involves doing a number of different things.", 1.0, "task variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 23.0, "The research position requires the performance of a wide range of tasks.", 1.0, "task variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 24.0, "The research position involves performing a variety of tasks.", 1.0, "task variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 25.0, "The results of my work are likely to significantly affect the lives of other people.", 1.0, "task significance");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 26.0, "The research position itself is very significant and important in the broader scheme of things.", 1.0, "task significance");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 27.0, "The research position has a large impact on people outside the organization.", 1.0, "task significance");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 28.0, "The work performed in the research position has a significant impact on people outside my research group.", 1.0, "task significance");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 29.0, "The research position involves completing a piece of work that has an obvious beginning and end.", 1.0, "task identity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 30.0, "The research position is arranged so that I can do an entire piece of work from beginning to end.", 1.0, "task identity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 31.0, "The research position provides me the chance to completely finish the pieces of work I begin.", 1.0, "task identity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 32.0, "The research position allows me to complete work I start.", 1.0, "task identity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 33.0, "The work activities themselves provide direct and clear information about the effectiveness (e.g., quality and quantity) of my performance.", 1.0, "feedback from job");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 34.0, "The research position itself provides feedback on my performance.", 1.0, "feedback from job");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 35.0, "The research position itself provides me with information about my performance.", 1.0, "feedback from job");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 36.0, "The research position requires that I only do one task or activity at a time.", 1.0, "job complexity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 37.0, "The tasks of the research position are simple and uncomplicated.", 1.0, "job complexity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 38.0, "The research position comprises relatively uncomplicated tasks.", 1.0, "job complexity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 39.0, "The research position involves performing relatively simple tasks.", 1.0, "job complexity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 40.0, "The research position requires me to monitor a great deal of information.", 1.0, "information processing");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 41.0, "The research position requires that I engage in a large amount of thinking.", 1.0, "information processing");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 42.0, "The research position requires me to keep track of more than one thing at a time.", 1.0, "information processing");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 43.0, "The research position requires me to analyze a lot of information.", 1.0, "information processing");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 44.0, "The research position involves solving problems that have no obvious correct answer.", 1.0, "problem solving");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 45.0, "The research position requires me to be creative.", 1.0, "problem solving");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 46.0, "The research position often involves dealing with problems that I have not met before.", 1.0, "problem solving");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 47.0, "The research position requires unique ideas or solutions to problems.", 1.0, "problem solving");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 48.0, "The research position requires a variety of skills.", 1.0, "skill variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 49.0, "The research position requires me to utilize a variety of different skills in order to complete the work.", 1.0, "skill variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 50.0, "The research position requires me to use a number of complex or high-level skills.", 1.0, "skill variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 51.0, "The research position requires the use of a number of skills.", 1.0, "skill variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 52.0, "The research position is highly specialized in terms of purpose, tasks, or activities.", 1.0, "specialization");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 53.0, "The tools, procedures, materials, and so forth used in this research position are highly specialized in terms of purpose.", 1.0, "specialization");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 54.0, "The research position requires very specialized knowledge and skills.", 1.0, "specialization");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 55.0, "The research position requires a depth of knowledge and expertise.", 1.0, "specialization");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 56.0, "I have the opportunity to develop close friendships in this research position.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 57.0, "I have the chance in this research position to get to know other people.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 58.0, "I have the opportunity to meet with others in this research position.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 59.0, "My group leader is concerned about the welfare of the people in the research group.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 60.0, "People I work with take a personal interest in me.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 61.0, "People I work with are friendly.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 62.0, "The research position requires me to accomplish my work before others complete their work.", 1.0, "initiated interdependence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 63.0, "Other jobs depend directly on my job.", 1.0, "initiated interdepenence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 64.0, "Unless my job gets done, other jobs cannot be completed.", 1.0, "initiated interdependence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 65.0, "My research activities are greatly affected by the work of other people.", 1.0, "received interdependence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 66.0, "The research project depends on the work of many different people for its completion.", 1.0, "received interdependence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 67.0, "My work cannot be done unless others do their work.", 1.0, "received interdependence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 68.0, "The research position requires spending a great deal of time with people outside my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 69.0, "The research position involves interaction with people who are not members of my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 70.0, "In this research position, I frequently communicate with people who do not work in the same research group as I do.", 1.0, "interaction outside research group");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 71.0, "The research position involves a great deal of interaction with people outside my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 72.0, "I receive a great deal of information from my project leader and peers about my work performance.", 1.0, "feedback from others");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 73.0, "Other people in the research group, such as group leader and peers, provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "feedback from others");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 74.0, "I receive feedback on my performance from other people in my group (such as my project leader or peers).", 1.0, "feedback from others");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 75.0, "I receive a great deal of information from my group leader about my work performance.", 1.0, "faculty/project leader feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 76.0, "My group leader provides information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "faculty/projecdt leader feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 77.0, "I receive feedback on my performance from my group leader.", 1.0, "faculty/project leader feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 78.0, "I receive a great deal of information from other students in my group about my work performance.", 1.0, "peer feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 79.0, "Other students in the research group provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "peer feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 80.0, "I receive feedback on my performance from other students in my group.", 1.0, "peer feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 81.0, "The seating arrangements in my research space are adequate (e.g., ample opportunities to sit, comfortable chairs, good postural support).", 1.0, "ergonomics");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 82.0, "The research space allows for all size differences between people in terms of clearance, reach, eye height, legroom, etc.", 1.0, "ergonomics");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 83.0, "The research position involves excessive reaching.", 1.0, "ergonomics");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 84.0, "The research position requires a great deal of muscular endurance.", 1.0, "physical demands");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 85.0, "The research position requires a great deal of muscular strength.", 1.0, "physical demands");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 86.0, "The research position requires a lot of physical effort.", 1.0, "physical demands");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 87.0, "The research space is free from excessive noise.", 1.0, "work conditions");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 88.0, "The climate in the research space is comfortable in terms of temperature and humidity.", 1.0, "work conditions");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 89.0, "The research position has a low risk of accident.", 1.0, "work conditions");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 90.0, "The research position takes place in an environment free from health hazards (e.g., chemicals, fumes, etc.).", 1.0, "work conditions");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 91.0, "The research position occurs in a clean environment.", 1.0, "work conditions");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 92.0, "The research position involves the use of a variety of different equipment.", 1.0, "equipment use");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 93.0, "The research position involves the use of complex equipment or technology.", 1.0, "equipment use");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (1.0, 94.0, "A lot of time was required to learn the equipment used in the research position.", 1.0, "equipment use");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 1.0, "What type of organization do you work in?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 2.0, "Which of degrees did you earn and what year did you earn them in (fill all that apply)", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 3.0, "In which year did you work at the position for which you are answering the survey?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 4.0, "How do you spend your time in this job (fieldwork)?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (None, 5.0, "How do you spend your time in this job (lab work)?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (None, 6.0, "How do you spend your time in this job (computer work)?", 0.0, Null);
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 7.0, "The job allows me to make my own decisions about how to schedule my work.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 8.0, "The job allows me to decide on the order in which things are done.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 9.0, "The job allows me to plan how I do my work.", 1.0, "work scheduling autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 10.0, "The job gives me a chance to use my personal initiative or judgment in carrying out the work.", 1.0, "decision making autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 11.0, "The job allows me to make a lot of decisions on my own.", 1.0, "decision making autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 12.0, "The job provides me with significant autonomy in making decisions.", 1.0, "decision making autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 13.0, "The job allows me to make decisions about what methods I use to complete my work.", 1.0, "work methods autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 14.0, "The job gives me considerable opportunity for independence and freedom in how I do the work.", 1.0, "work methods autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 15.0, "The job allows me to decide on my own how to go about doing my work.", 1.0, "work methods autonomy");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 16.0, "The job involves a great deal of task variety.", 1.0, "task variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 17.0, "The job involves doing a number of different things.", 1.0, "task variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 18.0, "The job requires the performance of a wide range of tasks.", 1.0, "task variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 19.0, "The job involves performing a variety of tasks.", 1.0, "task variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 20.0, "The results of my work are likely to significantly affect the lives of other people.", 1.0, "task significance");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 21.0, "The job itself is very significant and important in the broader scheme of things.", 1.0, "task significance");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 22.0, "The job has a large impact on people outside the organization.", 1.0, "task significance");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 23.0, "The work performed in the job has a significant impact on people outside my research group.", 1.0, "task significance");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 24.0, "The job involves completing a piece of work that has an obvious beginning and end.", 1.0, "task identity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 25.0, "The job is arranged so that I can do an entire piece of work from beginning to end.", 1.0, "task identity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 26.0, "The job provides me the chance to completely finish the pieces of work I begin.", 1.0, "task identity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 27.0, "The job allows me to complete work I start.", 1.0, "task identity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 28.0, "The work activities themselves provide direct and clear information about the effectiveness (e.g., quality and quantity) of my performance.", 1.0, "feedback from job");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 29.0, "The job itself provides feedback on my performance.", 1.0, "feedback from job");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 30.0, "The job itself provides me with information about my performance.", 1.0, "feedback from job");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 31.0, "The job requires that I only do one task or activity at a time.", 1.0, "job complexity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 32.0, "The tasks of the job are simple and uncomplicated.", 1.0, "job complexity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 33.0, "The job comprises relatively uncomplicated tasks.", 1.0, "job complexity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 34.0, "The job involves performing relatively simple tasks.", 1.0, "job complexity");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 35.0, "The job requires me to monitor a great deal of information.", 1.0, "information processing");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 36.0, "The job requires that I engage in a large amount of thinking.", 1.0, "information processing");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 37.0, "The job requires me to keep track of more than one thing at a time.", 1.0, "information processing");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 38.0, "The job requires me to analyze a lot of information.", 1.0, "information processing");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 39.0, "The job involves solving problems that have no obvious correct answer.", 1.0, "problem solving");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 40.0, "The job requires me to be creative.", 1.0, "problem solving");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 41.0, "The job often involves dealing with problems that I have not met before.", 1.0, "problem solving");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 42.0, "The job requires unique ideas or solutions to problems.", 1.0, "problem solving");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 43.0, "The job requires a variety of skills.", 1.0, "skill variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 44.0, "The job requires me to utilize a variety of different skills in order to complete the work.", 1.0, "skill variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 45.0, "The job requires me to use a number of complex or high-level skills.", 1.0, "skill variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 46.0, "The job requires the use of a number of skills.", 1.0, "skill variety");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 47.0, "The job is highly specialized in terms of purpose, tasks, or activities.", 1.0, "specialization");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 48.0, "The tools, procedures, materials, and so forth used in this job are highly specialized in terms of purpose.", 1.0, "specialization");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 49.0, "The job requires very specialized knowledge and skills.", 1.0, "specialization");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 50.0, "The job requires a depth of knowledge and expertise.", 1.0, "specialization");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 51.0, "I have the opportunity to develop close friendships in this job.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 52.0, "I have the chance in this job to get to know other people.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 53.0, "I have the opportunity to meet with others in this job.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 54.0, "My group leader is concerned about the welfare of the people in the research group.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 55.0, "People I work with take a personal interest in me.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 56.0, "People I work with are friendly.", 1.0, "social support");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 57.0, "The job requires me to accomplish my work before others complete their work.", 1.0, "initiated interdependence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 58.0, "Other jobs depend directly on my job.", 1.0, "initiated interdepenence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 59.0, "Unless my job gets done, other jobs cannot be completed.", 1.0, "initiated interdependence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 60.0, "My research activities are greatly affected by the work of other people.", 1.0, "received interdependence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 61.0, "The research project depends on the work of many different people for its completion.", 1.0, "received interdependence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 62.0, "My work cannot be done unless others do their work.", 1.0, "received interdependence");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 63.0, "The job requires spending a great deal of time with people outside my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 64.0, "The job involves interaction with people who are not members of my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 65.0, "In this job, I frequently communicate with people who do not work in the same research group as I do.", 1.0, "interaction outside research group");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 66.0, "The job involves a great deal of interaction with people outside my research group.", 1.0, "interaction outside research group");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 67.0, "I receive a great deal of information from my project leader and peers about my work performance.", 1.0, "feedback from others");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 68.0, "Other people in the research group, such as group leader and peers, provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "feedback from others");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 69.0, "I receive feedback on my performance from other people in my group (such as my project leader or peers).", 1.0, "feedback from others");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 70.0, "I receive a great deal of information from my group leader about my work performance.", 1.0, "faculty/project leader feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 71.0, "My group leader provides information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "faculty/projecdt leader feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 72.0, "I receive feedback on my performance from my group leader.", 1.0, "faculty/project leader feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 73.0, "I receive a great deal of information from other students in my group about my work performance.", 1.0, "peer feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 74.0, "Other students in the research group provide information about the effectiveness (e.g., quality and quantity) of my work performance.", 1.0, "peer feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 75.0, "I receive feedback on my performance from other students in my group.", 1.0, "peer feedback");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 76.0, "The seating arrangements in my research space are adequate (e.g., ample opportunities to sit, comfortable chairs, good postural support).", 1.0, "ergonomics");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 77.0, "The research space allows for all size differences between people in terms of clearance, reach, eye height, legroom, etc.", 1.0, "ergonomics");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 78.0, "The job involves excessive reaching.", 1.0, "ergonomics");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 79.0, "The job requires a great deal of muscular endurance.", 1.0, "physical demands");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 80.0, "The job requires a great deal of muscular strength.", 1.0, "physical demands");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 81.0, "The job requires a lot of physical effort.", 1.0, "physical demands");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 82.0, "The research space is free from excessive noise.", 1.0, "work conditions");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 83.0, "The climate in the research space is comfortable in terms of temperature and humidity.", 1.0, "work conditions");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 84.0, "The job has a low risk of accident.", 1.0, "work conditions");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 85.0, "The job takes place in an environment free from health hazards (e.g., chemicals, fumes, etc.).", 1.0, "work conditions");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 86.0, "The job occurs in a clean environment.", 1.0, "work conditions");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 87.0, "The job involves the use of a variety of different equipment.", 1.0, "equipment use");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 88.0, "The job involves the use of complex equipment or technology.", 1.0, "equipment use");
INSERT INTO Questions (SurveyId, QNumber, Text, Type, JobDescriptor) VALUES (2.0, 89.0, "A lot of time was required to learn the equipment used in the job.", 1.0, "equipment use");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (None, None, None, Null);
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 1.0, "Agriculture");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 2.0, "Bioinformatics and/or computational biology");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 3.0, "Discipline-based education research (DBER)");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 4.0, "Engineering");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 5.0, "Computer science and computer engineering");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 6.0, "Engineering - Biomedical");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 7.0, "Engineering (other)");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 8.0, "Environmental science");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 9.0, "Kinesiology");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 10.0, "anatomy and physiology ");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 11.0, "biochemistry");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 12.0, "general biology");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 13.0, "botany");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 14.0, "ecology");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 15.0, "evolution");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 16.0, "genetics ");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 17.0, "zoology");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 18.0, "Marine science");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 19.0, "Mathematics");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 20.0, "Neuroscience");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 21.0, "Physical Sciences:");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 22.0, "Astronomy");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 23.0, "Chemistry ");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 24.0, "Physics");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 25.0, "Geology");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 26.0, "Soil science");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 27.0, "Statistics and/or Data Science");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 28.0, "Other");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 1.0, 0.0, "prefer not to say");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 2.0, 1.0, "1 student");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 2.0, 2.0, "2-4 students");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 2.0, 3.0, "5-8 students");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 2.0, 4.0, "9-12 students");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 2.0, 5.0, "more than 12 students");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 2.0, 0.0, "prefer not to say");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 3.0, 1.0, "2 ");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 3.0, 2.0, "3-5 ");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 3.0, 3.0, "6-9");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 3.0, 4.0, "10-13");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 3.0, 5.0, "More than 13");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 3.0, 0.0, "prefer not to say");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 4.0, 1.0, "Faculty member");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 4.0, 2.0, "Postdoctoral researcher");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 4.0, 3.0, "Graduate student, technician, or staff scientist");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 4.0, 4.0, "Other");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 4.0, 0.0, "prefer not to say");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 5.0, 1.0, "Laboratory research");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 5.0, 2.0, "Field research");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 5.0, 3.0, "Computer-based research");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 5.0, 0.0, "prefer not to say");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 6.0, 1.0, "0 hours a week");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 6.0, 2.0, "1 - 5 hours a week");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 6.0, 3.0, "6 - 10 hours a week");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 6.0, 4.0, "11 - 15 hours a week");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 6.0, 5.0, "16 - 20 hours a week");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 6.0, 6.0, "21 - 25 hours a week");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 6.0, 7.0, "26 - 30 hours a week");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 6.0, 8.0, "more than 30 hours a week");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 6.0, 0.0, "Prefer not to say");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 12.0, 1.0, " strongly disagree ");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 12.0, 2.0, " disagree");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 12.0, 3.0, " somewhat disagree");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 12.0, 4.0, " neither agree nor disagree ");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 12.0, 5.0, " somewhat agree ");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 12.0, 6.0, "agree");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 12.0, 7.0, "strongly agree");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (1.0, 12.0, 0.0, "Prefer not to answer");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 1.0, 1.0, "Academic (college or university)");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 1.0, 2.0, "Industry - research and development");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 1.0, 3.0, "Industry - production and quality control");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 1.0, 4.0, "Government ");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 1.0, 5.0, "Self-employed consulting/fee for service");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 1.0, 6.0, "Other");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 1.0, 0.0, "Prefer not to answer");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 2.0, 1.0, "AA - year");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 2.0, 2.0, "Baccalaureate - year");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 2.0, 3.0, "Masters of Science");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 2.0, 4.0, "Ph. D");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 2.0, 5.0, "JD");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 2.0, 6.0, "MD");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 2.0, 7.0, "MBA");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 2.0, 8.0, "not applicable ");
INSERT INTO Choices (SurveyId, QuestionId, CNumber, Value) VALUES (2.0, 2.0, 0.0, "Prefer not to answer");
